### ISSUE TITLE
class ImproveMyCV

### ISSUE THREAD

**Issue by gianfranco-s** [gianfranco-s/improve-my-cv#1]
Given a JSON-like string (`original_json_cv`)

- add a context
- add a prompt template
- add a job_description_text
- the response (`improved_json_cv`) should be JSON-like, with the same fields as the original JSON, but with the updated values

Should not be changed from the original
- JSON field names
- Dates
- User data (name, phone, url, location, profiles

Either we check the response, or we don't send these fields to the model.

**Comment by gianfranco-s** [comment]
Let's do this using TDD

**Comment by matiasfalconaro** [comment]
Perhaps, exploring a mixture of direct JSON manipulation and utilizing a Modelfile could offer a balanced approach, combining precise control with tailored updates.

**Comment by gianfranco-s** [comment]
Do you think we should integrate the Modelfile here, or can we leave it for a later step, as an enhancement?

**Comment by matiasfalconaro** [comment]
It might be considered starting with direct JSON manipulation for simplicity. Both approaches will require testing, but it's worth keeping in mind that integrating a Modelfile could be a useful option later, especially if we find ourselves needing to adjust intrinsic parameters, as in a configuration file, to get a response as specific as we need.
